name: Test compute binary sizes

on:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    name: Build artifacts
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build main
        run: |
          New-Item -ItemType directory build
          gcc test/main.c -o build/main

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build

  compute_binary_sizes:
    name: Compute binary sizes
    needs: [build]
    uses: ./.github/workflows/compute-binary-sizes.yml
    with:
      artifact: binaries

